// This file represents the expected structure for Contentlayer types
// Actual types will be generated by Contentlayer at build time

export interface ContentlayerPaper {
  /** The title of the paper */
  title: string
  /** The description/abstract of the paper */
  description: string
  /** The authors of the paper as a semicolon-separated string */
  authors: string
  /** The URL to the original paper */
  url?: string
  /** The publication year of the paper */
  year?: number
  /** The journal where the paper was published */
  journal?: string
  /** The DOI of the paper */
  doi?: string
  /** The keywords for the paper as a semicolon-separated string */
  keywords?: string
  /** The number of citations */
  citations: number
  /** The ID of the paper */
  _id: string
  /** The slug of the paper */
  slug: string
  /** Computed field: parsed authors as an array */
  parsedAuthors: string[]
  /** Computed field: parsed keywords as an array */
  parsedKeywords: string[]
  /** The full content of the paper */
  body: {
    raw: string
    code: string
  }
  /** Word count of the paper */
  wordCount: number
  /** Reading time in minutes */
  readingTime: number
  /** The file path of the paper */
  filePath: string
  /** The source file path */
  sourceFilePath: string
  /** The title without extension */
  titleWithoutExt: string
}